events {}
http {
  server {
    listen 8080;
    location / {
      proxy_pass http://192.168.0.20:31549;
    }
  }
  server {
    listen 8081;
    location / {
      proxy_pass http://192.168.0.20:32389;
    }
  }
}
