all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
  hosts:

    control-plane:
      ansible_host: 192.168.0.20 
    worker-01:
      ansible_host: 192.168.0.21
    worker-02:
      ansible_host: 192.168.0.22
 
  children:
    kube_control_plane:
      hosts: 
        control-plane:
        
    kube_node:
      hosts:
        worker-01: 
        worker-02: 
         
    k8s_cluster:
      children:
        kube_control_plane: 
        kube_node: 
    etcd:
      hosts:
        control-plane:
        
